# Loading Data

In [313]:
import sys
from pathlib import Path
import logging
import pandas as pd

# Add src directory to Python path
sys.path.append(str(Path.cwd().parent/"src"))

# Import our custom loader
from data_loader import BloodDonationDataLoader

# Initialize loader
loader = BloodDonationDataLoader()

# Load data
raw_data = loader.load_raw_excel()

# Verify
print("Loaded sheets:", list(raw_data.keys()))
print("\n2019 columns:", raw_data["2019"].columns.tolist())
display(raw_data["Volontaire"].head())

Successfully loaded Excel file: /home/alphonse/github-repos/00_blood_campaign_dashboard/blood_donation_campaign_dashboard/data/raw/blood_donation_data.xlsx
Successfully loaded Excel file: /home/alphonse/github-repos/00_blood_campaign_dashboard/blood_donation_campaign_dashboard/data/raw/blood_donation_data.xlsx
Successfully loaded Excel file: /home/alphonse/github-repos/00_blood_campaign_dashboard/blood_donation_campaign_dashboard/data/raw/blood_donation_data.xlsx
Successfully loaded Excel file: /home/alphonse/github-repos/00_blood_campaign_dashboard/blood_donation_campaign_dashboard/data/raw/blood_donation_data.xlsx
Successfully loaded Excel file: /home/alphonse/github-repos/00_blood_campaign_dashboard/blood_donation_campaign_dashboard/data/raw/blood_donation_data.xlsx
Successfully loaded Excel file: /home/alphonse/github-repos/00_blood_campaign_dashboard/blood_donation_campaign_dashboard/data/raw/blood_donation_data.xlsx
Successfully loaded Excel file: /home/alphonse/github-repos/00_blood_campaign_dashboard/blood_donation_campaign_dashboard/data/raw/blood_donation_data.xlsx
Successfully loaded Excel file: /home/alphonse/github-repos/00_blood_campaign_dashboard/blood_donation_campaign_dashboard/data/raw/blood_donation_data.xlsx

Loaded sheets: ['2019', '2020', 'Volontaire']

2019 columns: ['Date de remplissage de la fiche', 'Date de naissance', "Niveau d'etude", 'Genre', 'Taille', 'Poids', 'Situation Matrimoniale (SM)', 'Profession', 'Arrondissement de résidence', 'Quartier de Résidence', 'Nationalité', 'Religion', 'A-t-il (elle) déjà donné le sang', 'Si oui preciser la date du dernier don.', 'Taux d’hémoglobine', 'ÉLIGIBILITÉ AU DON.', 'Raison indisponibilité  [Est sous anti-biothérapie  ]', 'Raison indisponibilité  [Taux d’hémoglobine bas ]', 'Raison indisponibilité  [date de dernier Don < 3 mois ]', 'Raison indisponibilité  [IST récente (Exclu VIH, Hbs, Hcv)]', 'Date de dernières règles (DDR) ', 'Raison de l’indisponibilité de la femme [La DDR est mauvais si <14 jour avant le don]', 'Raison de l’indisponibilité de la femme [Allaitement ]', 'Raison de l’indisponibilité de la femme [A accoucher ces 6 derniers mois  ]', 'Raison de l’indisponibilité de la femme [Interruption de grossesse  ces 06 derniers mois]', 'Raison de l’indisponibilité de la femme [est enceinte ]', 'Autre raisons,  preciser', 'Sélectionner "ok" pour envoyer', 'Raison de non-eligibilité totale  [Antécédent de transfusion]', 'Raison de non-eligibilité totale  [Porteur(HIV,hbs,hcv)]', 'Raison de non-eligibilité totale  [Opéré]', 'Raison de non-eligibilité totale  [Drepanocytaire]', 'Raison de non-eligibilité totale  [Diabétique]', 'Raison de non-eligibilité totale  [Hypertendus]', 'Raison de non-eligibilité totale  [Asthmatiques]', 'Raison de non-eligibilité totale  [Cardiaque]', 'Raison de non-eligibilité totale  [Tatoué]', 'Raison de non-eligibilité totale  [Scarifié]', 'Si autres raison préciser']

,ID,Age,Horodateur,Niveau_d'etude,Genre_,Taille_,Poids,Situation_Matrimoniale_(SM),Profession_,Arrondissement_de_résidence_,...,"Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]",Raison_de_non-eligibilité_totale__[Opéré],Raison_de_non-eligibilité_totale__[Drepanocytaire],Raison_de_non-eligibilité_totale__[Diabétique],Raison_de_non-eligibilité_totale__[Hypertendus],Raison_de_non-eligibilité_totale__[Asthmatiques],Raison_de_non-eligibilité_totale__[Cardiaque],Raison_de_non-eligibilité_totale__[Tatoué],Raison_de_non-eligibilité_totale__[Scarifié],Si_autres_raison_préciser_
0,DONOR_1842,24,46:44.9,Universitaire,Homme,,,Célibataire,Etudiant (e),Douala 3,...,,,,,,,,,,
1,DONOR_1843,23,44:19.0,Universitaire,Homme,,,Célibataire,Sans Emplois,R A S,...,Non,Oui,Non,Non,Non,Non,Non,Non,Non,
2,DONOR_1844,41,46:54.3,Aucun,Homme,,,Marié (e),Tailleur,Douala 1,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Aucune information
3,DONOR_1845,24,29:29.7,Universitaire,Homme,,,Célibataire,Etudiant,Douala 5,...,,,,,,,,,,
4,DONOR_1846,30,47:47.4,Secondaire,Homme,,,Célibataire,Militaire,Douala (Non précisé ),...,,,,,,,,,,

In [314]:
interim = raw_data.copy()

In [315]:
columns_2019 = interim["2019"].columns.tolist()

In [316]:
# Columns in sheet "Volontaire"
columns_volontaire = interim["Volontaire"].columns.tolist()
print(columns_volontaire)

['ID', 'Age', 'Horodateur', "Niveau_d'etude", 'Genre_', 'Taille_', 'Poids', 'Situation_Matrimoniale_(SM)', 'Profession_', 'Arrondissement_de_résidence_', 'Quartier_de_Résidence_', 'Nationalité_', 'Religion_', 'A-t-il_(elle)_déjà_donné_le_sang_', 'Si_oui_preciser_la_date_du_dernier_don._', 'Taux_d’hémoglobine_', 'ÉLIGIBILITÉ_AU_DON.', 'Raison_indisponibilité__[Est_sous_anti-biothérapie__]', 'Raison_indisponibilité__[Taux_d’hémoglobine_bas_]', 'Raison_indisponibilité__[date_de_dernier_Don_<_3_mois_]', 'Raison_indisponibilité__[IST_récente_(Exclu_VIH,_Hbs,_Hcv)]', 'Date_de_dernières_règles_(DDR)__', 'Raison_de_l’indisponibilité_de_la_femme_[La_DDR_est_mauvais_si_<14_jour_avant_le_don]', 'Raison_de_l’indisponibilité_de_la_femme_[Allaitement_]', 'Raison_de_l’indisponibilité_de_la_femme_[A_accoucher_ces_6_derniers_mois__]', 'Raison_de_l’indisponibilité_de_la_femme_[Interruption_de_grossesse__ces_06_derniers_mois]', 'Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]', 'Autre_raisons,__preciser_', 'Sélectionner_"ok"_pour_envoyer_', 'Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion]', 'Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]', 'Raison_de_non-eligibilité_totale__[Opéré]', 'Raison_de_non-eligibilité_totale__[Drepanocytaire]', 'Raison_de_non-eligibilité_totale__[Diabétique]', 'Raison_de_non-eligibilité_totale__[Hypertendus]', 'Raison_de_non-eligibilité_totale__[Asthmatiques]', 'Raison_de_non-eligibilité_totale__[Cardiaque]', 'Raison_de_non-eligibilité_totale__[Tatoué]', 'Raison_de_non-eligibilité_totale__[Scarifié]', 'Si_autres_raison_préciser_']

In [317]:
# Columns present in 2019 sheet but not in Volontaire
columns_2019_not_in_volontaire = [col for col in columns_2019 if col not in columns_volontaire]
print("Columns in 2019 but not in Volontaire:", columns_2019_not_in_volontaire)

# Columns present in Volontaire sheet but not in 2019
columns_volontaire_not_in_2019 = [col for col in columns_volontaire if col not in columns_2019]
print("Columns in Volontaire but not in 2019:", columns_volontaire_not_in_2019)

Columns in 2019 but not in Volontaire: ['Date de remplissage de la fiche', 'Date de naissance', "Niveau d'etude", 'Genre', 'Taille', 'Situation Matrimoniale (SM)', 'Profession', 'Arrondissement de résidence', 'Quartier de Résidence', 'Nationalité', 'Religion', 'A-t-il (elle) déjà donné le sang', 'Si oui preciser la date du dernier don.', 'Taux d’hémoglobine', 'ÉLIGIBILITÉ AU DON.', 'Raison indisponibilité  [Est sous anti-biothérapie  ]', 'Raison indisponibilité  [Taux d’hémoglobine bas ]', 'Raison indisponibilité  [date de dernier Don < 3 mois ]', 'Raison indisponibilité  [IST récente (Exclu VIH, Hbs, Hcv)]', 'Date de dernières règles (DDR) ', 'Raison de l’indisponibilité de la femme [La DDR est mauvais si <14 jour avant le don]', 'Raison de l’indisponibilité de la femme [Allaitement ]', 'Raison de l’indisponibilité de la femme [A accoucher ces 6 derniers mois  ]', 'Raison de l’indisponibilité de la femme [Interruption de grossesse  ces 06 derniers mois]', 'Raison de l’indisponibilité de la femme [est enceinte ]', 'Autre raisons,  preciser', 'Sélectionner "ok" pour envoyer', 'Raison de non-eligibilité totale  [Antécédent de transfusion]', 'Raison de non-eligibilité totale  [Porteur(HIV,hbs,hcv)]', 'Raison de non-eligibilité totale  [Opéré]', 'Raison de non-eligibilité totale  [Drepanocytaire]', 'Raison de non-eligibilité totale  [Diabétique]', 'Raison de non-eligibilité totale  [Hypertendus]', 'Raison de non-eligibilité totale  [Asthmatiques]', 'Raison de non-eligibilité totale  [Cardiaque]', 'Raison de non-eligibilité totale  [Tatoué]', 'Raison de non-eligibilité totale  [Scarifié]', 'Si autres raison préciser']
Columns in Volontaire but not in 2019: ['ID', 'Age', 'Horodateur', "Niveau_d'etude", 'Genre_', 'Taille_', 'Situation_Matrimoniale_(SM)', 'Profession_', 'Arrondissement_de_résidence_', 'Quartier_de_Résidence_', 'Nationalité_', 'Religion_', 'A-t-il_(elle)_déjà_donné_le_sang_', 'Si_oui_preciser_la_date_du_dernier_don._', 'Taux_d’hémoglobine_', 'ÉLIGIBILITÉ_AU_DON.', 'Raison_indisponibilité__[Est_sous_anti-biothérapie__]', 'Raison_indisponibilité__[Taux_d’hémoglobine_bas_]', 'Raison_indisponibilité__[date_de_dernier_Don_<_3_mois_]', 'Raison_indisponibilité__[IST_récente_(Exclu_VIH,_Hbs,_Hcv)]', 'Date_de_dernières_règles_(DDR)__', 'Raison_de_l’indisponibilité_de_la_femme_[La_DDR_est_mauvais_si_<14_jour_avant_le_don]', 'Raison_de_l’indisponibilité_de_la_femme_[Allaitement_]', 'Raison_de_l’indisponibilité_de_la_femme_[A_accoucher_ces_6_derniers_mois__]', 'Raison_de_l’indisponibilité_de_la_femme_[Interruption_de_grossesse__ces_06_derniers_mois]', 'Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]', 'Autre_raisons,__preciser_', 'Sélectionner_"ok"_pour_envoyer_', 'Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion]', 'Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]', 'Raison_de_non-eligibilité_totale__[Opéré]', 'Raison_de_non-eligibilité_totale__[Drepanocytaire]', 'Raison_de_non-eligibilité_totale__[Diabétique]', 'Raison_de_non-eligibilité_totale__[Hypertendus]', 'Raison_de_non-eligibilité_totale__[Asthmatiques]', 'Raison_de_non-eligibilité_totale__[Cardiaque]', 'Raison_de_non-eligibilité_totale__[Tatoué]', 'Raison_de_non-eligibilité_totale__[Scarifié]', 'Si_autres_raison_préciser_']

In [318]:
interim["Volontaire"].head()

,ID,Age,Horodateur,Niveau_d'etude,Genre_,Taille_,Poids,Situation_Matrimoniale_(SM),Profession_,Arrondissement_de_résidence_,...,"Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]",Raison_de_non-eligibilité_totale__[Opéré],Raison_de_non-eligibilité_totale__[Drepanocytaire],Raison_de_non-eligibilité_totale__[Diabétique],Raison_de_non-eligibilité_totale__[Hypertendus],Raison_de_non-eligibilité_totale__[Asthmatiques],Raison_de_non-eligibilité_totale__[Cardiaque],Raison_de_non-eligibilité_totale__[Tatoué],Raison_de_non-eligibilité_totale__[Scarifié],Si_autres_raison_préciser_
0,DONOR_1842,24,46:44.9,Universitaire,Homme,,,Célibataire,Etudiant (e),Douala 3,...,,,,,,,,,,
1,DONOR_1843,23,44:19.0,Universitaire,Homme,,,Célibataire,Sans Emplois,R A S,...,Non,Oui,Non,Non,Non,Non,Non,Non,Non,
2,DONOR_1844,41,46:54.3,Aucun,Homme,,,Marié (e),Tailleur,Douala 1,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Aucune information
3,DONOR_1845,24,29:29.7,Universitaire,Homme,,,Célibataire,Etudiant,Douala 5,...,,,,,,,,,,
4,DONOR_1846,30,47:47.4,Secondaire,Homme,,,Célibataire,Militaire,Douala (Non précisé ),...,,,,,,,,,,

In [319]:
interim["Volontaire"].columns.tolist()

['ID',
 'Age',
 'Horodateur',
 "Niveau_d'etude",
 'Genre_',
 'Taille_',
 'Poids',
 'Situation_Matrimoniale_(SM)',
 'Profession_',
 'Arrondissement_de_résidence_',
 'Quartier_de_Résidence_',
 'Nationalité_',
 'Religion_',
 'A-t-il_(elle)_déjà_donné_le_sang_',
 'Si_oui_preciser_la_date_du_dernier_don._',
 'Taux_d’hémoglobine_',
 'ÉLIGIBILITÉ_AU_DON.',
 'Raison_indisponibilité__[Est_sous_anti-biothérapie__]',
 'Raison_indisponibilité__[Taux_d’hémoglobine_bas_]',
 'Raison_indisponibilité__[date_de_dernier_Don_<_3_mois_]',
 'Raison_indisponibilité__[IST_récente_(Exclu_VIH,_Hbs,_Hcv)]',
 'Date_de_dernières_règles_(DDR)__',
 'Raison_de_l’indisponibilité_de_la_femme_[La_DDR_est_mauvais_si_<14_jour_avant_le_don]',
 'Raison_de_l’indisponibilité_de_la_femme_[Allaitement_]',
 'Raison_de_l’indisponibilité_de_la_femme_[A_accoucher_ces_6_derniers_mois__]',
 'Raison_de_l’indisponibilité_de_la_femme_[Interruption_de_grossesse__ces_06_derniers_mois]',
 'Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]',
 'Autre_raisons,__preciser_',
 'Sélectionner_"ok"_pour_envoyer_',
 'Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion]',
 'Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]',
 'Raison_de_non-eligibilité_totale__[Opéré]',
 'Raison_de_non-eligibilité_totale__[Drepanocytaire]',
 'Raison_de_non-eligibilité_totale__[Diabétique]',
 'Raison_de_non-eligibilité_totale__[Hypertendus]',
 'Raison_de_non-eligibilité_totale__[Asthmatiques]',
 'Raison_de_non-eligibilité_totale__[Cardiaque]',
 'Raison_de_non-eligibilité_totale__[Tatoué]',
 'Raison_de_non-eligibilité_totale__[Scarifié]',
 'Si_autres_raison_préciser_']

In [320]:
# Drop the "Horodateur" column from the "Volontaire" sheet
interim["Volontaire"].drop(columns=["Horodateur"], inplace=True)

# Verify the column has been dropped
print(interim["Volontaire"].columns.tolist())

['ID', 'Age', "Niveau_d'etude", 'Genre_', 'Taille_', 'Poids', 'Situation_Matrimoniale_(SM)', 'Profession_', 'Arrondissement_de_résidence_', 'Quartier_de_Résidence_', 'Nationalité_', 'Religion_', 'A-t-il_(elle)_déjà_donné_le_sang_', 'Si_oui_preciser_la_date_du_dernier_don._', 'Taux_d’hémoglobine_', 'ÉLIGIBILITÉ_AU_DON.', 'Raison_indisponibilité__[Est_sous_anti-biothérapie__]', 'Raison_indisponibilité__[Taux_d’hémoglobine_bas_]', 'Raison_indisponibilité__[date_de_dernier_Don_<_3_mois_]', 'Raison_indisponibilité__[IST_récente_(Exclu_VIH,_Hbs,_Hcv)]', 'Date_de_dernières_règles_(DDR)__', 'Raison_de_l’indisponibilité_de_la_femme_[La_DDR_est_mauvais_si_<14_jour_avant_le_don]', 'Raison_de_l’indisponibilité_de_la_femme_[Allaitement_]', 'Raison_de_l’indisponibilité_de_la_femme_[A_accoucher_ces_6_derniers_mois__]', 'Raison_de_l’indisponibilité_de_la_femme_[Interruption_de_grossesse__ces_06_derniers_mois]', 'Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]', 'Autre_raisons,__preciser_', 'Sélectionner_"ok"_pour_envoyer_', 'Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion]', 'Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]', 'Raison_de_non-eligibilité_totale__[Opéré]', 'Raison_de_non-eligibilité_totale__[Drepanocytaire]', 'Raison_de_non-eligibilité_totale__[Diabétique]', 'Raison_de_non-eligibilité_totale__[Hypertendus]', 'Raison_de_non-eligibilité_totale__[Asthmatiques]', 'Raison_de_non-eligibilité_totale__[Cardiaque]', 'Raison_de_non-eligibilité_totale__[Tatoué]', 'Raison_de_non-eligibilité_totale__[Scarifié]', 'Si_autres_raison_préciser_']

In [321]:
# Remove trailing underscores from column names in the "Volontaire" sheet
interim["Volontaire"].columns = [col.rstrip('_') for col in interim["Volontaire"].columns]

# Verify the changes
print(interim["Volontaire"].columns.tolist())

['ID', 'Age', "Niveau_d'etude", 'Genre', 'Taille', 'Poids', 'Situation_Matrimoniale_(SM)', 'Profession', 'Arrondissement_de_résidence', 'Quartier_de_Résidence', 'Nationalité', 'Religion', 'A-t-il_(elle)_déjà_donné_le_sang', 'Si_oui_preciser_la_date_du_dernier_don.', 'Taux_d’hémoglobine', 'ÉLIGIBILITÉ_AU_DON.', 'Raison_indisponibilité__[Est_sous_anti-biothérapie__]', 'Raison_indisponibilité__[Taux_d’hémoglobine_bas_]', 'Raison_indisponibilité__[date_de_dernier_Don_<_3_mois_]', 'Raison_indisponibilité__[IST_récente_(Exclu_VIH,_Hbs,_Hcv)]', 'Date_de_dernières_règles_(DDR)', 'Raison_de_l’indisponibilité_de_la_femme_[La_DDR_est_mauvais_si_<14_jour_avant_le_don]', 'Raison_de_l’indisponibilité_de_la_femme_[Allaitement_]', 'Raison_de_l’indisponibilité_de_la_femme_[A_accoucher_ces_6_derniers_mois__]', 'Raison_de_l’indisponibilité_de_la_femme_[Interruption_de_grossesse__ces_06_derniers_mois]', 'Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]', 'Autre_raisons,__preciser', 'Sélectionner_"ok"_pour_envoyer', 'Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion]', 'Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]', 'Raison_de_non-eligibilité_totale__[Opéré]', 'Raison_de_non-eligibilité_totale__[Drepanocytaire]', 'Raison_de_non-eligibilité_totale__[Diabétique]', 'Raison_de_non-eligibilité_totale__[Hypertendus]', 'Raison_de_non-eligibilité_totale__[Asthmatiques]', 'Raison_de_non-eligibilité_totale__[Cardiaque]', 'Raison_de_non-eligibilité_totale__[Tatoué]', 'Raison_de_non-eligibilité_totale__[Scarifié]', 'Si_autres_raison_préciser']

In [322]:
# Show descriptive statistics of the "Volontaire" dataset
volontaire_stats = interim["Volontaire"].describe(include='all')
print(volontaire_stats)

                ID   Age Niveau_d'etude  Genre Taille Poids  \
count         1846  1846           1846   1846   1846  1846
unique        1846    51              5      2     25    41
top     DONOR_3687    30     Secondaire  Homme
freq             1   106            673   1664   1786  1742

       Situation_Matrimoniale_(SM)    Profession Arrondissement_de_résidence  \
count                         1846          1846                        1846
unique                           4           520                          41
top                    Célibataire  Etudiant (e)       Douala (Non précisé )
freq                          1365           276                         951

       Quartier_de_Résidence  ...  \
count                   1846  ...
unique                   576  ...
top                   Douala  ...
freq                     175  ...

       Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]  \
count                                                1846
unique                                                  3
top
freq                                                 1768

       Raison_de_non-eligibilité_totale__[Opéré]  \
count                                       1846
unique                                         3
top
freq                                        1768

       Raison_de_non-eligibilité_totale__[Drepanocytaire]  \
count                                                1846
unique                                                  3
top
freq                                                 1768

       Raison_de_non-eligibilité_totale__[Diabétique]  \
count                                            1846
unique                                              3
top
freq                                             1768

       Raison_de_non-eligibilité_totale__[Hypertendus]  \
count                                             1846
unique                                               3
top
freq                                              1768

       Raison_de_non-eligibilité_totale__[Asthmatiques]  \
count                                              1846
unique                                                3
top
freq                                               1768

       Raison_de_non-eligibilité_totale__[Cardiaque]  \
count                                           1846
unique                                             3
top
freq                                            1768

       Raison_de_non-eligibilité_totale__[Tatoué]  \
count                                        1846
unique                                          3
top
freq                                         1768

       Raison_de_non-eligibilité_totale__[Scarifié] Si_autres_raison_préciser
count                                          1846                      1846
unique                                            3                        14
top
freq                                           1768                      1833

[4 rows x 39 columns]

In [323]:
# Remove trailing periods from column names in the "Volontaire" sheet
interim["Volontaire"].columns = [col.rstrip('.') for col in interim["Volontaire"].columns]

# Verify the changes
print(interim["Volontaire"].columns.tolist())

['ID', 'Age', "Niveau_d'etude", 'Genre', 'Taille', 'Poids', 'Situation_Matrimoniale_(SM)', 'Profession', 'Arrondissement_de_résidence', 'Quartier_de_Résidence', 'Nationalité', 'Religion', 'A-t-il_(elle)_déjà_donné_le_sang', 'Si_oui_preciser_la_date_du_dernier_don', 'Taux_d’hémoglobine', 'ÉLIGIBILITÉ_AU_DON', 'Raison_indisponibilité__[Est_sous_anti-biothérapie__]', 'Raison_indisponibilité__[Taux_d’hémoglobine_bas_]', 'Raison_indisponibilité__[date_de_dernier_Don_<_3_mois_]', 'Raison_indisponibilité__[IST_récente_(Exclu_VIH,_Hbs,_Hcv)]', 'Date_de_dernières_règles_(DDR)', 'Raison_de_l’indisponibilité_de_la_femme_[La_DDR_est_mauvais_si_<14_jour_avant_le_don]', 'Raison_de_l’indisponibilité_de_la_femme_[Allaitement_]', 'Raison_de_l’indisponibilité_de_la_femme_[A_accoucher_ces_6_derniers_mois__]', 'Raison_de_l’indisponibilité_de_la_femme_[Interruption_de_grossesse__ces_06_derniers_mois]', 'Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]', 'Autre_raisons,__preciser', 'Sélectionner_"ok"_pour_envoyer', 'Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion]', 'Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]', 'Raison_de_non-eligibilité_totale__[Opéré]', 'Raison_de_non-eligibilité_totale__[Drepanocytaire]', 'Raison_de_non-eligibilité_totale__[Diabétique]', 'Raison_de_non-eligibilité_totale__[Hypertendus]', 'Raison_de_non-eligibilité_totale__[Asthmatiques]', 'Raison_de_non-eligibilité_totale__[Cardiaque]', 'Raison_de_non-eligibilité_totale__[Tatoué]', 'Raison_de_non-eligibilité_totale__[Scarifié]', 'Si_autres_raison_préciser']

In [324]:
# Convert columns to numeric
interim["Volontaire"]["Age"] = pd.to_numeric(interim["Volontaire"]["Age"], errors='coerce')
interim["Volontaire"]["Taille"] = pd.to_numeric(interim["Volontaire"]["Taille"], errors='coerce')
interim["Volontaire"]["Poids"] = pd.to_numeric(interim["Volontaire"]["Poids"], errors='coerce')

# Verify the changes
print(interim["Volontaire"][["Age", "Taille", "Poids"]].dtypes)

Age         int64
Taille    float64
Poids     float64
dtype: object

In [325]:
# Replace missing values in 'Poids' with the mean of the column
mean_poids = interim["Volontaire"]["Poids"].astype(float).mean()
interim["Volontaire"]["Poids"] = interim["Volontaire"]["Poids"].fillna(mean_poids)

print("Number of missing values in 'Poids' after replacement:", interim["Volontaire"]["Poids"].isnull().sum())

Number of missing values in 'Poids' after replacement: 0

In [326]:
# Replace missing values in 'Age' with the mean of the column
mean_age = interim["Volontaire"]["Age"].astype(float).mean()
interim["Volontaire"]["Age"] = interim["Volontaire"]["Age"].fillna(mean_age)

print("Number of missing values in 'Age' after replacement:", interim["Volontaire"]["Age"].isnull().sum())

Number of missing values in 'Age' after replacement: 0

In [327]:
# Replace missing values in 'Taille' with the mean of the column
mean_taille = interim["Volontaire"]["Taille"].astype(float).mean()
interim["Volontaire"]["Taille"] = interim["Volontaire"]["Taille"].fillna(mean_taille)

print("Number of missing values in 'Taille' after replacement:", interim["Volontaire"]["Taille"].isnull().sum())

Number of missing values in 'Taille' after replacement: 0

In [328]:
# check for missing values in the 'Taille' column
print("Number of missing values in 'Taille':", interim["Volontaire"]["Taille"].isnull().sum())

Number of missing values in 'Taille': 0

In [329]:
# check for missing values in the 'Poids' column
print("Number of missing values in 'Poids':", interim["Volontaire"]["Poids"].isnull().sum())

Number of missing values in 'Poids': 0

In [330]:
# Drop the "Date_de_dernières_règles_(DDR)" column from the "Volontaire" sheet
interim["Volontaire"].drop(columns=["Date_de_dernières_règles_(DDR)"], inplace=True)

# Verify the column has been dropped
print(interim["Volontaire"].columns.tolist())

['ID', 'Age', "Niveau_d'etude", 'Genre', 'Taille', 'Poids', 'Situation_Matrimoniale_(SM)', 'Profession', 'Arrondissement_de_résidence', 'Quartier_de_Résidence', 'Nationalité', 'Religion', 'A-t-il_(elle)_déjà_donné_le_sang', 'Si_oui_preciser_la_date_du_dernier_don', 'Taux_d’hémoglobine', 'ÉLIGIBILITÉ_AU_DON', 'Raison_indisponibilité__[Est_sous_anti-biothérapie__]', 'Raison_indisponibilité__[Taux_d’hémoglobine_bas_]', 'Raison_indisponibilité__[date_de_dernier_Don_<_3_mois_]', 'Raison_indisponibilité__[IST_récente_(Exclu_VIH,_Hbs,_Hcv)]', 'Raison_de_l’indisponibilité_de_la_femme_[La_DDR_est_mauvais_si_<14_jour_avant_le_don]', 'Raison_de_l’indisponibilité_de_la_femme_[Allaitement_]', 'Raison_de_l’indisponibilité_de_la_femme_[A_accoucher_ces_6_derniers_mois__]', 'Raison_de_l’indisponibilité_de_la_femme_[Interruption_de_grossesse__ces_06_derniers_mois]', 'Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]', 'Autre_raisons,__preciser', 'Sélectionner_"ok"_pour_envoyer', 'Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion]', 'Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]', 'Raison_de_non-eligibilité_totale__[Opéré]', 'Raison_de_non-eligibilité_totale__[Drepanocytaire]', 'Raison_de_non-eligibilité_totale__[Diabétique]', 'Raison_de_non-eligibilité_totale__[Hypertendus]', 'Raison_de_non-eligibilité_totale__[Asthmatiques]', 'Raison_de_non-eligibilité_totale__[Cardiaque]', 'Raison_de_non-eligibilité_totale__[Tatoué]', 'Raison_de_non-eligibilité_totale__[Scarifié]', 'Si_autres_raison_préciser']

In [331]:
# Filter columns that start with "Raison_de"
raison_de_columns = [col for col in columns_volontaire if col.startswith("Raison")]
print("Columns that start with 'Raison':", raison_de_columns)

Columns that start with 'Raison': ['Raison_indisponibilité__[Est_sous_anti-biothérapie__]', 'Raison_indisponibilité__[Taux_d’hémoglobine_bas_]', 'Raison_indisponibilité__[date_de_dernier_Don_<_3_mois_]', 'Raison_indisponibilité__[IST_récente_(Exclu_VIH,_Hbs,_Hcv)]', 'Raison_de_l’indisponibilité_de_la_femme_[La_DDR_est_mauvais_si_<14_jour_avant_le_don]', 'Raison_de_l’indisponibilité_de_la_femme_[Allaitement_]', 'Raison_de_l’indisponibilité_de_la_femme_[A_accoucher_ces_6_derniers_mois__]', 'Raison_de_l’indisponibilité_de_la_femme_[Interruption_de_grossesse__ces_06_derniers_mois]', 'Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]', 'Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion]', 'Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]', 'Raison_de_non-eligibilité_totale__[Opéré]', 'Raison_de_non-eligibilité_totale__[Drepanocytaire]', 'Raison_de_non-eligibilité_totale__[Diabétique]', 'Raison_de_non-eligibilité_totale__[Hypertendus]', 'Raison_de_non-eligibilité_totale__[Asthmatiques]', 'Raison_de_non-eligibilité_totale__[Cardiaque]', 'Raison_de_non-eligibilité_totale__[Tatoué]', 'Raison_de_non-eligibilité_totale__[Scarifié]']

In [332]:
# Fill missing values in the columns listed in raison_de_columns with "Non"
interim["Volontaire"][raison_de_columns] = interim["Volontaire"][raison_de_columns].fillna("Non")

# Verify the changes
print(interim["Volontaire"][raison_de_columns].isnull().sum())

Raison_indisponibilité__[Est_sous_anti-biothérapie__]                                        0
Raison_indisponibilité__[Taux_d’hémoglobine_bas_]                                            0
Raison_indisponibilité__[date_de_dernier_Don_<_3_mois_]                                      0
Raison_indisponibilité__[IST_récente_(Exclu_VIH,_Hbs,_Hcv)]                                  0
Raison_de_l’indisponibilité_de_la_femme_[La_DDR_est_mauvais_si_<14_jour_avant_le_don]        0
Raison_de_l’indisponibilité_de_la_femme_[Allaitement_]                                       0
Raison_de_l’indisponibilité_de_la_femme_[A_accoucher_ces_6_derniers_mois__]                  0
Raison_de_l’indisponibilité_de_la_femme_[Interruption_de_grossesse__ces_06_derniers_mois]    0
Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]                                      0
Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion]                                0
Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]                                     0
Raison_de_non-eligibilité_totale__[Opéré]                                                    0
Raison_de_non-eligibilité_totale__[Drepanocytaire]                                           0
Raison_de_non-eligibilité_totale__[Diabétique]                                               0
Raison_de_non-eligibilité_totale__[Hypertendus]                                              0
Raison_de_non-eligibilité_totale__[Asthmatiques]                                             0
Raison_de_non-eligibilité_totale__[Cardiaque]                                                0
Raison_de_non-eligibilité_totale__[Tatoué]                                                   0
Raison_de_non-eligibilité_totale__[Scarifié]                                                 0
dtype: int64

In [333]:
interim["Volontaire"].head(5)

,ID,Age,Niveau_d'etude,Genre,Taille,Poids,Situation_Matrimoniale_(SM),Profession,Arrondissement_de_résidence,Quartier_de_Résidence,...,"Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]",Raison_de_non-eligibilité_totale__[Opéré],Raison_de_non-eligibilité_totale__[Drepanocytaire],Raison_de_non-eligibilité_totale__[Diabétique],Raison_de_non-eligibilité_totale__[Hypertendus],Raison_de_non-eligibilité_totale__[Asthmatiques],Raison_de_non-eligibilité_totale__[Cardiaque],Raison_de_non-eligibilité_totale__[Tatoué],Raison_de_non-eligibilité_totale__[Scarifié],Si_autres_raison_préciser
0,DONOR_1842,24,Universitaire,Homme,172.816667,77.278846,Célibataire,Etudiant (e),Douala 3,Yassa,...,,,,,,,,,,
1,DONOR_1843,23,Universitaire,Homme,172.816667,77.278846,Célibataire,Sans Emplois,R A S,R A S,...,Non,Oui,Non,Non,Non,Non,Non,Non,Non,
2,DONOR_1844,41,Aucun,Homme,172.816667,77.278846,Marié (e),Tailleur,Douala 1,NEW BELL,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Aucune information
3,DONOR_1845,24,Universitaire,Homme,172.816667,77.278846,Célibataire,Etudiant,Douala 5,Ange raphael,...,,,,,,,,,,
4,DONOR_1846,30,Secondaire,Homme,172.816667,77.278846,Célibataire,Militaire,Douala (Non précisé ),Beedi,...,,,,,,,,,,

In [334]:
missing_values_scarifie = interim["Volontaire"]["Raison_de_non-eligibilité_totale__[Scarifié]"].isnull().sum()
print("Number of missing values in 'Raison_de_non-eligibilité_totale__[Scarifié]':", missing_values_scarifie)

Number of missing values in 'Raison_de_non-eligibilité_totale__[Scarifié]': 0

In [335]:
interim["Volontaire"]["Raison_de_non-eligibilité_totale__[Scarifié]"].describe()

count     1846
unique       3
top
freq      1768
Name: Raison_de_non-eligibilité_totale__[Scarifié], dtype: object

In [336]:
unique_values_scarifie = interim["Volontaire"]["Raison_de_non-eligibilité_totale__[Scarifié]"].unique()
print("Unique values in 'Raison_de_non-eligibilité_totale__[Scarifié]':", unique_values_scarifie)

Unique values in 'Raison_de_non-eligibilité_totale__[Scarifié]': ['' 'Non' 'Oui']

In [337]:
empty_values_scarifie = interim["Volontaire"]["Raison_de_non-eligibilité_totale__[Scarifié]"].value_counts().get('', 0)
print("Number of empty string values in 'Raison_de_non-eligibilité_totale__[Scarifié]':", empty_values_scarifie)

Number of empty string values in 'Raison_de_non-eligibilité_totale__[Scarifié]': 1768

In [338]:
interim["Volontaire"]["Raison_de_non-eligibilité_totale__[Scarifié]"].replace('', 'Non', inplace=True)

# Verify the changes
print(interim["Volontaire"]["Raison_de_non-eligibilité_totale__[Scarifié]"].value_counts())

Raison_de_non-eligibilité_totale__[Scarifié]
Non    1836
Oui      10
Name: count, dtype: int64

/tmp/ipykernel_3588/3701494528.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  interim["Volontaire"]["Raison_de_non-eligibilité_totale__[Scarifié]"].replace('', 'Non', inplace=True)

In [339]:
interim["Volontaire"]["Raison_de_non-eligibilité_totale__[Scarifié]"].head(10)

0    Non
1    Non
2    Non
3    Non
4    Non
5    Non
6    Non
7    Non
8    Non
9    Non
Name: Raison_de_non-eligibilité_totale__[Scarifié], dtype: object

In [340]:
# Replace all '' values in 'raison_de_columns' columns with 'Non'
interim["Volontaire"][raison_de_columns] = interim["Volontaire"][raison_de_columns].replace('', 'Non')

# Verify the changes
print(interim["Volontaire"][raison_de_columns].isnull().sum())

Raison_indisponibilité__[Est_sous_anti-biothérapie__]                                        0
Raison_indisponibilité__[Taux_d’hémoglobine_bas_]                                            0
Raison_indisponibilité__[date_de_dernier_Don_<_3_mois_]                                      0
Raison_indisponibilité__[IST_récente_(Exclu_VIH,_Hbs,_Hcv)]                                  0
Raison_de_l’indisponibilité_de_la_femme_[La_DDR_est_mauvais_si_<14_jour_avant_le_don]        0
Raison_de_l’indisponibilité_de_la_femme_[Allaitement_]                                       0
Raison_de_l’indisponibilité_de_la_femme_[A_accoucher_ces_6_derniers_mois__]                  0
Raison_de_l’indisponibilité_de_la_femme_[Interruption_de_grossesse__ces_06_derniers_mois]    0
Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]                                      0
Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion]                                0
Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]                                     0
Raison_de_non-eligibilité_totale__[Opéré]                                                    0
Raison_de_non-eligibilité_totale__[Drepanocytaire]                                           0
Raison_de_non-eligibilité_totale__[Diabétique]                                               0
Raison_de_non-eligibilité_totale__[Hypertendus]                                              0
Raison_de_non-eligibilité_totale__[Asthmatiques]                                             0
Raison_de_non-eligibilité_totale__[Cardiaque]                                                0
Raison_de_non-eligibilité_totale__[Tatoué]                                                   0
Raison_de_non-eligibilité_totale__[Scarifié]                                                 0
dtype: int64

In [341]:
interim["Volontaire"]["Raison_de_non-eligibilité_totale__[Tatoué]"].value_counts()

Raison_de_non-eligibilité_totale__[Tatoué]
Non    1835
Oui      11
Name: count, dtype: int64

In [342]:
interim["Volontaire"]["Raison_de_non-eligibilité_totale__[Tatoué]"].head()

0    Non
1    Non
2    Non
3    Non
4    Non
Name: Raison_de_non-eligibilité_totale__[Tatoué], dtype: object

In [343]:
interim["Volontaire"]["Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]"].unique()

array(['Non'], dtype=object)

In [344]:
unique_values_scarifie = interim["Volontaire"]["Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]"].unique()
print("Unique values in 'Raison_de_non-eligibilité_totale__[Scarifié]':", unique_values_scarifie)

Unique values in 'Raison_de_non-eligibilité_totale__[Scarifié]': ['Non']

In [345]:
interim["Volontaire"].head(10)

,ID,Age,Niveau_d'etude,Genre,Taille,Poids,Situation_Matrimoniale_(SM),Profession,Arrondissement_de_résidence,Quartier_de_Résidence,...,"Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]",Raison_de_non-eligibilité_totale__[Opéré],Raison_de_non-eligibilité_totale__[Drepanocytaire],Raison_de_non-eligibilité_totale__[Diabétique],Raison_de_non-eligibilité_totale__[Hypertendus],Raison_de_non-eligibilité_totale__[Asthmatiques],Raison_de_non-eligibilité_totale__[Cardiaque],Raison_de_non-eligibilité_totale__[Tatoué],Raison_de_non-eligibilité_totale__[Scarifié],Si_autres_raison_préciser
0,DONOR_1842,24,Universitaire,Homme,172.816667,77.278846,Célibataire,Etudiant (e),Douala 3,Yassa,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,
1,DONOR_1843,23,Universitaire,Homme,172.816667,77.278846,Célibataire,Sans Emplois,R A S,R A S,...,Non,Oui,Non,Non,Non,Non,Non,Non,Non,
2,DONOR_1844,41,Aucun,Homme,172.816667,77.278846,Marié (e),Tailleur,Douala 1,NEW BELL,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Aucune information
3,DONOR_1845,24,Universitaire,Homme,172.816667,77.278846,Célibataire,Etudiant,Douala 5,Ange raphael,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,
4,DONOR_1846,30,Secondaire,Homme,172.816667,77.278846,Célibataire,Militaire,Douala (Non précisé ),Beedi,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,
5,DONOR_1847,28,Universitaire,Homme,172.816667,77.278846,Célibataire,Etudiant (e),Douala (Non précisé ),Deido,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,
6,DONOR_1848,34,Primaire,Homme,172.816667,77.278846,Marié (e),Sans Emplois,Douala (Non précisé ),Henry,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,
7,DONOR_1849,31,Pas Précisé,Homme,172.816667,77.278846,Marié (e),Bijoutier,Non précisé,Non précisé,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,
8,DONOR_1850,22,Secondaire,Homme,172.816667,77.278846,Célibataire,Couturier,Douala 2,Ancien 3ieme,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,
9,DONOR_1851,32,Universitaire,Homme,172.816667,77.278846,Marié (e),Jeune cadre,Douala 3,ndogpassi,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,

In [346]:
missing_values = interim["Volontaire"].isnull().sum()
columns_with_missing_values = missing_values[missing_values > 0]
print("Columns with missing values:", columns_with_missing_values)

Columns with missing values: Series([], dtype: int64)

In [347]:
interim["Volontaire"].isnull().sum()

ID                                                                                           0
Age                                                                                          0
Niveau_d'etude                                                                               0
Genre                                                                                        0
Taille                                                                                       0
Poids                                                                                        0
Situation_Matrimoniale_(SM)                                                                  0
Profession                                                                                   0
Arrondissement_de_résidence                                                                  0
Quartier_de_Résidence                                                                        0
Nationalité                                                                                  0
Religion                                                                                     0
A-t-il_(elle)_déjà_donné_le_sang                                                             0
Si_oui_preciser_la_date_du_dernier_don                                                       0
Taux_d’hémoglobine                                                                           0
ÉLIGIBILITÉ_AU_DON                                                                           0
Raison_indisponibilité__[Est_sous_anti-biothérapie__]                                        0
Raison_indisponibilité__[Taux_d’hémoglobine_bas_]                                            0
Raison_indisponibilité__[date_de_dernier_Don_<_3_mois_]                                      0
Raison_indisponibilité__[IST_récente_(Exclu_VIH,_Hbs,_Hcv)]                                  0
Raison_de_l’indisponibilité_de_la_femme_[La_DDR_est_mauvais_si_<14_jour_avant_le_don]        0
Raison_de_l’indisponibilité_de_la_femme_[Allaitement_]                                       0
Raison_de_l’indisponibilité_de_la_femme_[A_accoucher_ces_6_derniers_mois__]                  0
Raison_de_l’indisponibilité_de_la_femme_[Interruption_de_grossesse__ces_06_derniers_mois]    0
Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]                                      0
Autre_raisons,__preciser                                                                     0
Sélectionner_"ok"_pour_envoyer                                                               0
Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion]                                0
Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]                                     0
Raison_de_non-eligibilité_totale__[Opéré]                                                    0
Raison_de_non-eligibilité_totale__[Drepanocytaire]                                           0
Raison_de_non-eligibilité_totale__[Diabétique]                                               0
Raison_de_non-eligibilité_totale__[Hypertendus]                                              0
Raison_de_non-eligibilité_totale__[Asthmatiques]                                             0
Raison_de_non-eligibilité_totale__[Cardiaque]                                                0
Raison_de_non-eligibilité_totale__[Tatoué]                                                   0
Raison_de_non-eligibilité_totale__[Scarifié]                                                 0
Si_autres_raison_préciser                                                                    0
dtype: int64

In [348]:
# Drop the "Si_autres_raison_préciser" column from the "Volontaire" sheet
interim["Volontaire"].drop(columns=["Si_autres_raison_préciser"], inplace=True)

# Verify the column has been dropped
print(interim["Volontaire"].columns.tolist())

['ID', 'Age', "Niveau_d'etude", 'Genre', 'Taille', 'Poids', 'Situation_Matrimoniale_(SM)', 'Profession', 'Arrondissement_de_résidence', 'Quartier_de_Résidence', 'Nationalité', 'Religion', 'A-t-il_(elle)_déjà_donné_le_sang', 'Si_oui_preciser_la_date_du_dernier_don', 'Taux_d’hémoglobine', 'ÉLIGIBILITÉ_AU_DON', 'Raison_indisponibilité__[Est_sous_anti-biothérapie__]', 'Raison_indisponibilité__[Taux_d’hémoglobine_bas_]', 'Raison_indisponibilité__[date_de_dernier_Don_<_3_mois_]', 'Raison_indisponibilité__[IST_récente_(Exclu_VIH,_Hbs,_Hcv)]', 'Raison_de_l’indisponibilité_de_la_femme_[La_DDR_est_mauvais_si_<14_jour_avant_le_don]', 'Raison_de_l’indisponibilité_de_la_femme_[Allaitement_]', 'Raison_de_l’indisponibilité_de_la_femme_[A_accoucher_ces_6_derniers_mois__]', 'Raison_de_l’indisponibilité_de_la_femme_[Interruption_de_grossesse__ces_06_derniers_mois]', 'Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]', 'Autre_raisons,__preciser', 'Sélectionner_"ok"_pour_envoyer', 'Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion]', 'Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]', 'Raison_de_non-eligibilité_totale__[Opéré]', 'Raison_de_non-eligibilité_totale__[Drepanocytaire]', 'Raison_de_non-eligibilité_totale__[Diabétique]', 'Raison_de_non-eligibilité_totale__[Hypertendus]', 'Raison_de_non-eligibilité_totale__[Asthmatiques]', 'Raison_de_non-eligibilité_totale__[Cardiaque]', 'Raison_de_non-eligibilité_totale__[Tatoué]', 'Raison_de_non-eligibilité_totale__[Scarifié]']

In [349]:
# Drop the "Autre_raisons,__preciser" column from the "Volontaire" sheet
interim["Volontaire"].drop(columns=["Autre_raisons,__preciser"], inplace=True)

# Verify the column has been dropped
print(interim["Volontaire"].columns.tolist())

['ID', 'Age', "Niveau_d'etude", 'Genre', 'Taille', 'Poids', 'Situation_Matrimoniale_(SM)', 'Profession', 'Arrondissement_de_résidence', 'Quartier_de_Résidence', 'Nationalité', 'Religion', 'A-t-il_(elle)_déjà_donné_le_sang', 'Si_oui_preciser_la_date_du_dernier_don', 'Taux_d’hémoglobine', 'ÉLIGIBILITÉ_AU_DON', 'Raison_indisponibilité__[Est_sous_anti-biothérapie__]', 'Raison_indisponibilité__[Taux_d’hémoglobine_bas_]', 'Raison_indisponibilité__[date_de_dernier_Don_<_3_mois_]', 'Raison_indisponibilité__[IST_récente_(Exclu_VIH,_Hbs,_Hcv)]', 'Raison_de_l’indisponibilité_de_la_femme_[La_DDR_est_mauvais_si_<14_jour_avant_le_don]', 'Raison_de_l’indisponibilité_de_la_femme_[Allaitement_]', 'Raison_de_l’indisponibilité_de_la_femme_[A_accoucher_ces_6_derniers_mois__]', 'Raison_de_l’indisponibilité_de_la_femme_[Interruption_de_grossesse__ces_06_derniers_mois]', 'Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]', 'Sélectionner_"ok"_pour_envoyer', 'Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion]', 'Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]', 'Raison_de_non-eligibilité_totale__[Opéré]', 'Raison_de_non-eligibilité_totale__[Drepanocytaire]', 'Raison_de_non-eligibilité_totale__[Diabétique]', 'Raison_de_non-eligibilité_totale__[Hypertendus]', 'Raison_de_non-eligibilité_totale__[Asthmatiques]', 'Raison_de_non-eligibilité_totale__[Cardiaque]', 'Raison_de_non-eligibilité_totale__[Tatoué]', 'Raison_de_non-eligibilité_totale__[Scarifié]']

In [350]:
# Drop the "Sélectionner_"ok"_pour_envoyer" column from the "Volontaire" sheet
interim["Volontaire"].drop(columns=['Sélectionner_"ok"_pour_envoyer'], inplace=True)

# Verify the column has been dropped
print(interim["Volontaire"].columns.tolist())

['ID', 'Age', "Niveau_d'etude", 'Genre', 'Taille', 'Poids', 'Situation_Matrimoniale_(SM)', 'Profession', 'Arrondissement_de_résidence', 'Quartier_de_Résidence', 'Nationalité', 'Religion', 'A-t-il_(elle)_déjà_donné_le_sang', 'Si_oui_preciser_la_date_du_dernier_don', 'Taux_d’hémoglobine', 'ÉLIGIBILITÉ_AU_DON', 'Raison_indisponibilité__[Est_sous_anti-biothérapie__]', 'Raison_indisponibilité__[Taux_d’hémoglobine_bas_]', 'Raison_indisponibilité__[date_de_dernier_Don_<_3_mois_]', 'Raison_indisponibilité__[IST_récente_(Exclu_VIH,_Hbs,_Hcv)]', 'Raison_de_l’indisponibilité_de_la_femme_[La_DDR_est_mauvais_si_<14_jour_avant_le_don]', 'Raison_de_l’indisponibilité_de_la_femme_[Allaitement_]', 'Raison_de_l’indisponibilité_de_la_femme_[A_accoucher_ces_6_derniers_mois__]', 'Raison_de_l’indisponibilité_de_la_femme_[Interruption_de_grossesse__ces_06_derniers_mois]', 'Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]', 'Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion]', 'Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]', 'Raison_de_non-eligibilité_totale__[Opéré]', 'Raison_de_non-eligibilité_totale__[Drepanocytaire]', 'Raison_de_non-eligibilité_totale__[Diabétique]', 'Raison_de_non-eligibilité_totale__[Hypertendus]', 'Raison_de_non-eligibilité_totale__[Asthmatiques]', 'Raison_de_non-eligibilité_totale__[Cardiaque]', 'Raison_de_non-eligibilité_totale__[Tatoué]', 'Raison_de_non-eligibilité_totale__[Scarifié]']

In [351]:
# Convert "Taux_d’hémoglobine" to float
interim["Volontaire"]["Taux_d’hémoglobine"] = pd.to_numeric(interim["Volontaire"]["Taux_d’hémoglobine"], errors='coerce')

# Calculate the mean value
mean_of_taux_hemoglobine = interim["Volontaire"]["Taux_d’hémoglobine"].mean().round(1)

# Fill missing values with the mean value
interim["Volontaire"]["Taux_d’hémoglobine"].fillna(mean_of_taux_hemoglobine, inplace=True)

# Verify the changes
print(interim["Volontaire"]["Taux_d’hémoglobine"].head())
print("Number of missing values in 'Taux_d’hémoglobine' after replacement:", interim["Volontaire"]["Taux_d’hémoglobine"].isnull().sum())

0    13.9
1    10.8
2    13.9
3    15.0
4    13.9
Name: Taux_d’hémoglobine, dtype: float64
Number of missing values in 'Taux_d’hémoglobine' after replacement: 0

/tmp/ipykernel_3588/2118007432.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  interim["Volontaire"]["Taux_d’hémoglobine"].fillna(mean_of_taux_hemoglobine, inplace=True)

In [352]:
# Check for columns with missing values in the "Volontaire" sheet
missing_values = interim["Volontaire"].isnull().sum()
columns_with_missing_values = missing_values[missing_values > 0]
print("Columns with missing values:", columns_with_missing_values)

Columns with missing values: Series([], dtype: int64)

In [353]:
# Remove strings ending with "(Non précisé )" in the "Arrondissement_de_résidence" column
interim["Volontaire"]["Arrondissement_de_résidence"] = interim["Volontaire"]["Arrondissement_de_résidence"].str.replace(r'\s*\(Non précisé \)$', '', regex=True)

# Verify the changes
print(interim["Volontaire"]["Arrondissement_de_résidence"].unique())

['Douala 3' 'R A S' 'Douala 1' 'Douala 5' 'Douala' 'Non précisé'
 'Douala 2' 'Douala 4' 'Yaounde' 'Meiganga' 'R A S ' 'Edea' 'RAS ' 'OYACK'
 'Ras' 'Manjo' 'Douala 6' 'Pas precise' 'TIKO' 'Pas précisé' 'Bafoussam'
 'RAS' 'BOKO' 'Kribi' 'West' 'Njombe' 'Nkouabang' 'Ngodi Bakoko '
 'non precisé' 'Buea' 'Dschang' 'Bomono Ba Mbegue' 'BUEA' 'DCANKONGMONDO'
 'LIMBE ' 'Pas précisé ' 'Deido' 'SUD OUEST TOMBEL' 'Pas mentionné'
 'Yaoundé']

Feature engineering

In [354]:
# Calculate IMC and add it as a new column
interim["Volontaire"]["IMC"] = (interim["Volontaire"]["Poids"] / (interim["Volontaire"]["Taille"] / 100) ** 2).round(2)

# Verify the changes
print(interim["Volontaire"][["Poids", "Taille", "IMC"]].head())

       Poids      Taille    IMC
0  77.278846  172.816667  25.88
1  77.278846  172.816667  25.88
2  77.278846  172.816667  25.88
3  77.278846  172.816667  25.88
4  77.278846  172.816667  25.88

In [355]:
# Fréquence_de_don
interim["Volontaire"]["Fréquence_de_don"] = interim["Volontaire"]["A-t-il_(elle)_déjà_donné_le_sang"].apply(lambda x: 1 if x == 'Oui' else 0)

In [356]:
# Drop the "Si_oui_preciser_la_date_du_dernier_don" column from the "Volontaire" sheet
interim["Volontaire"].drop(columns=["Si_oui_preciser_la_date_du_dernier_don"], inplace=True)

# Verify the column has been dropped
print(interim["Volontaire"].columns.tolist())

['ID', 'Age', "Niveau_d'etude", 'Genre', 'Taille', 'Poids', 'Situation_Matrimoniale_(SM)', 'Profession', 'Arrondissement_de_résidence', 'Quartier_de_Résidence', 'Nationalité', 'Religion', 'A-t-il_(elle)_déjà_donné_le_sang', 'Taux_d’hémoglobine', 'ÉLIGIBILITÉ_AU_DON', 'Raison_indisponibilité__[Est_sous_anti-biothérapie__]', 'Raison_indisponibilité__[Taux_d’hémoglobine_bas_]', 'Raison_indisponibilité__[date_de_dernier_Don_<_3_mois_]', 'Raison_indisponibilité__[IST_récente_(Exclu_VIH,_Hbs,_Hcv)]', 'Raison_de_l’indisponibilité_de_la_femme_[La_DDR_est_mauvais_si_<14_jour_avant_le_don]', 'Raison_de_l’indisponibilité_de_la_femme_[Allaitement_]', 'Raison_de_l’indisponibilité_de_la_femme_[A_accoucher_ces_6_derniers_mois__]', 'Raison_de_l’indisponibilité_de_la_femme_[Interruption_de_grossesse__ces_06_derniers_mois]', 'Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]', 'Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion]', 'Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]', 'Raison_de_non-eligibilité_totale__[Opéré]', 'Raison_de_non-eligibilité_totale__[Drepanocytaire]', 'Raison_de_non-eligibilité_totale__[Diabétique]', 'Raison_de_non-eligibilité_totale__[Hypertendus]', 'Raison_de_non-eligibilité_totale__[Asthmatiques]', 'Raison_de_non-eligibilité_totale__[Cardiaque]', 'Raison_de_non-eligibilité_totale__[Tatoué]', 'Raison_de_non-eligibilité_totale__[Scarifié]', 'IMC', 'Fréquence_de_don']

In [357]:
# Groupe_d'âge
bins = [18, 25, 35, 45, 55, 65, 75, 85, 95]
labels = ['18-25', '26-35', '36-45', '46-55', '56-65', '66-75', '76-85', '86-95']
interim["Volontaire"]["Groupe_d'âge"] = pd.cut(interim["Volontaire"]["Age"], bins=bins, labels=labels, right=False)

# Catégorie_d'IMC
IMC_bins = [0, 18.5, 24.9, 29.9, 39.9, 100]
IMC_labels = ['Insuffisance pondérale', 'Poids normal', 'Surpoids', 'Obèse', 'Obésité sévère']
interim["Volontaire"]["Catégorie_d'IMC"] = pd.cut(interim["Volontaire"]["IMC"], bins=IMC_bins, labels=IMC_labels, right=False)


# Statut_d'éligibilité
interim["Volontaire"]["Statut_d'éligibilité"] = interim["Volontaire"]["ÉLIGIBILITÉ_AU_DON"].apply(lambda x: 1 if x == 'Eligible' else 0)

# Catégorie_de_niveau_d'hémoglobine
hemoglobin_bins = [0, 12, 16, 20]
hemoglobin_labels = ['Bas', 'Normal', 'Élevé']
interim["Volontaire"]["Catégorie_de_niveau_d'hémoglobine"] = pd.cut(interim["Volontaire"]["Taux_d’hémoglobine"], bins=hemoglobin_bins, labels=hemoglobin_labels, right=False)

# Verify the changes
interim["Volontaire"].head()

,ID,Age,Niveau_d'etude,Genre,Taille,Poids,Situation_Matrimoniale_(SM),Profession,Arrondissement_de_résidence,Quartier_de_Résidence,...,Raison_de_non-eligibilité_totale__[Asthmatiques],Raison_de_non-eligibilité_totale__[Cardiaque],Raison_de_non-eligibilité_totale__[Tatoué],Raison_de_non-eligibilité_totale__[Scarifié],IMC,Fréquence_de_don,Groupe_d'âge,Catégorie_d'IMC,Statut_d'éligibilité,Catégorie_de_niveau_d'hémoglobine
0,DONOR_1842,24,Universitaire,Homme,172.816667,77.278846,Célibataire,Etudiant (e),Douala 3,Yassa,...,Non,Non,Non,Non,25.88,0,18-25,Surpoids,1,Normal
1,DONOR_1843,23,Universitaire,Homme,172.816667,77.278846,Célibataire,Sans Emplois,R A S,R A S,...,Non,Non,Non,Non,25.88,1,18-25,Surpoids,0,Bas
2,DONOR_1844,41,Aucun,Homme,172.816667,77.278846,Marié (e),Tailleur,Douala 1,NEW BELL,...,Non,Non,Non,Non,25.88,0,36-45,Surpoids,0,Normal
3,DONOR_1845,24,Universitaire,Homme,172.816667,77.278846,Célibataire,Etudiant,Douala 5,Ange raphael,...,Non,Non,Non,Non,25.88,0,18-25,Surpoids,1,Normal
4,DONOR_1846,30,Secondaire,Homme,172.816667,77.278846,Célibataire,Militaire,Douala,Beedi,...,Non,Non,Non,Non,25.88,1,26-35,Surpoids,1,Normal

In [358]:
interim["Volontaire"].columns.tolist()

['ID',
 'Age',
 "Niveau_d'etude",
 'Genre',
 'Taille',
 'Poids',
 'Situation_Matrimoniale_(SM)',
 'Profession',
 'Arrondissement_de_résidence',
 'Quartier_de_Résidence',
 'Nationalité',
 'Religion',
 'A-t-il_(elle)_déjà_donné_le_sang',
 'Taux_d’hémoglobine',
 'ÉLIGIBILITÉ_AU_DON',
 'Raison_indisponibilité__[Est_sous_anti-biothérapie__]',
 'Raison_indisponibilité__[Taux_d’hémoglobine_bas_]',
 'Raison_indisponibilité__[date_de_dernier_Don_<_3_mois_]',
 'Raison_indisponibilité__[IST_récente_(Exclu_VIH,_Hbs,_Hcv)]',
 'Raison_de_l’indisponibilité_de_la_femme_[La_DDR_est_mauvais_si_<14_jour_avant_le_don]',
 'Raison_de_l’indisponibilité_de_la_femme_[Allaitement_]',
 'Raison_de_l’indisponibilité_de_la_femme_[A_accoucher_ces_6_derniers_mois__]',
 'Raison_de_l’indisponibilité_de_la_femme_[Interruption_de_grossesse__ces_06_derniers_mois]',
 'Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]',
 'Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion]',
 'Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]',
 'Raison_de_non-eligibilité_totale__[Opéré]',
 'Raison_de_non-eligibilité_totale__[Drepanocytaire]',
 'Raison_de_non-eligibilité_totale__[Diabétique]',
 'Raison_de_non-eligibilité_totale__[Hypertendus]',
 'Raison_de_non-eligibilité_totale__[Asthmatiques]',
 'Raison_de_non-eligibilité_totale__[Cardiaque]',
 'Raison_de_non-eligibilité_totale__[Tatoué]',
 'Raison_de_non-eligibilité_totale__[Scarifié]',
 'IMC',
 'Fréquence_de_don',
 "Groupe_d'âge",
 "Catégorie_d'IMC",
 "Statut_d'éligibilité",
 "Catégorie_de_niveau_d'hémoglobine"]

In [359]:
# Define the new column order
new_column_order = [
    'ID', 'Age','Groupe_d\'âge', 'Taille', 'Poids', 'IMC', 'Catégorie_d\'IMC', 'Fréquence_de_don', 'Taux_d’hémoglobine', 'Catégorie_de_niveau_d\'hémoglobine', 'Statut_d\'éligibilité', 'ÉLIGIBILITÉ_AU_DON', 'Genre', 'Niveau_d\'etude', 'Situation_Matrimoniale_(SM)', 'Profession', 
    'Arrondissement_de_résidence', 'Quartier_de_Résidence', 'Nationalité', 'Religion', 
    'A-t-il_(elle)_déjà_donné_le_sang',  
    'Raison_indisponibilité__[Est_sous_anti-biothérapie__]', 'Raison_indisponibilité__[Taux_d’hémoglobine_bas_]', 
    'Raison_indisponibilité__[date_de_dernier_Don_<_3_mois_]', 'Raison_indisponibilité__[IST_récente_(Exclu_VIH,_Hbs,_Hcv)]', 
    'Raison_de_l’indisponibilité_de_la_femme_[La_DDR_est_mauvais_si_<14_jour_avant_le_don]', 
    'Raison_de_l’indisponibilité_de_la_femme_[Allaitement_]', 'Raison_de_l’indisponibilité_de_la_femme_[A_accoucher_ces_6_derniers_mois__]', 
    'Raison_de_l’indisponibilité_de_la_femme_[Interruption_de_grossesse__ces_06_derniers_mois]', 
    'Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]', 'Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion]', 
    'Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]', 'Raison_de_non-eligibilité_totale__[Opéré]', 
    'Raison_de_non-eligibilité_totale__[Drepanocytaire]', 'Raison_de_non-eligibilité_totale__[Diabétique]', 
    'Raison_de_non-eligibilité_totale__[Hypertendus]', 'Raison_de_non-eligibilité_totale__[Asthmatiques]', 
    'Raison_de_non-eligibilité_totale__[Cardiaque]', 'Raison_de_non-eligibilité_totale__[Tatoué]', 
    'Raison_de_non-eligibilité_totale__[Scarifié]',
]

# Reassign the dataframe with the new column order
interim["Volontaire"] = interim["Volontaire"][new_column_order]

# Verify the changes
interim["Volontaire"].head()

,ID,Age,Groupe_d'âge,Taille,Poids,IMC,Catégorie_d'IMC,Fréquence_de_don,Taux_d’hémoglobine,Catégorie_de_niveau_d'hémoglobine,...,Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion],"Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]",Raison_de_non-eligibilité_totale__[Opéré],Raison_de_non-eligibilité_totale__[Drepanocytaire],Raison_de_non-eligibilité_totale__[Diabétique],Raison_de_non-eligibilité_totale__[Hypertendus],Raison_de_non-eligibilité_totale__[Asthmatiques],Raison_de_non-eligibilité_totale__[Cardiaque],Raison_de_non-eligibilité_totale__[Tatoué],Raison_de_non-eligibilité_totale__[Scarifié]
0,DONOR_1842,24,18-25,172.816667,77.278846,25.88,Surpoids,0,13.9,Normal,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non
1,DONOR_1843,23,18-25,172.816667,77.278846,25.88,Surpoids,1,10.8,Bas,...,Non,Non,Oui,Non,Non,Non,Non,Non,Non,Non
2,DONOR_1844,41,36-45,172.816667,77.278846,25.88,Surpoids,0,13.9,Normal,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non
3,DONOR_1845,24,18-25,172.816667,77.278846,25.88,Surpoids,0,15.0,Normal,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non
4,DONOR_1846,30,26-35,172.816667,77.278846,25.88,Surpoids,1,13.9,Normal,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non

In [360]:
interim["Volontaire"].columns

Index(['ID', 'Age', 'Groupe_d'âge', 'Taille', 'Poids', 'IMC',
       'Catégorie_d'IMC', 'Fréquence_de_don', 'Taux_d’hémoglobine',
       'Catégorie_de_niveau_d'hémoglobine', 'Statut_d'éligibilité',
       'ÉLIGIBILITÉ_AU_DON', 'Genre', 'Niveau_d'etude',
       'Situation_Matrimoniale_(SM)', 'Profession',
       'Arrondissement_de_résidence', 'Quartier_de_Résidence', 'Nationalité',
       'Religion', 'A-t-il_(elle)_déjà_donné_le_sang',
       'Raison_indisponibilité__[Est_sous_anti-biothérapie__]',
       'Raison_indisponibilité__[Taux_d’hémoglobine_bas_]',
       'Raison_indisponibilité__[date_de_dernier_Don_<_3_mois_]',
       'Raison_indisponibilité__[IST_récente_(Exclu_VIH,_Hbs,_Hcv)]',
       'Raison_de_l’indisponibilité_de_la_femme_[La_DDR_est_mauvais_si_<14_jour_avant_le_don]',
       'Raison_de_l’indisponibilité_de_la_femme_[Allaitement_]',
       'Raison_de_l’indisponibilité_de_la_femme_[A_accoucher_ces_6_derniers_mois__]',
       'Raison_de_l’indisponibilité_de_la_femme_[Interruption_de_grossesse__ces_06_derniers_mois]',
       'Raison_de_l’indisponibilité_de_la_femme_[est_enceinte_]',
       'Raison_de_non-eligibilité_totale__[Antécédent_de_transfusion]',
       'Raison_de_non-eligibilité_totale__[Porteur(HIV,hbs,hcv)]',
       'Raison_de_non-eligibilité_totale__[Opéré]',
       'Raison_de_non-eligibilité_totale__[Drepanocytaire]',
       'Raison_de_non-eligibilité_totale__[Diabétique]',
       'Raison_de_non-eligibilité_totale__[Hypertendus]',
       'Raison_de_non-eligibilité_totale__[Asthmatiques]',
       'Raison_de_non-eligibilité_totale__[Cardiaque]',
       'Raison_de_non-eligibilité_totale__[Tatoué]',
       'Raison_de_non-eligibilité_totale__[Scarifié]'],
      dtype='object')

In [361]:
missing_values = interim["Volontaire"].isnull().sum()
columns_with_missing_values = missing_values[missing_values > 0]
print("Columns with missing values:", columns_with_missing_values)

Columns with missing values: Groupe_d'âge                         24
Catégorie_de_niveau_d'hémoglobine     3
dtype: int64

In [362]:
# Fill missing values in 'Groupe_d'âge' with the most frequent value
most_frequent_groupe_d_age = interim["Volontaire"]["Groupe_d'âge"].mode()[0]
interim["Volontaire"]["Groupe_d'âge"].fillna(most_frequent_groupe_d_age, inplace=True)

# Fill missing values in 'Catégorie_de_niveau_d'hémoglobine' with the most frequent value
most_frequent_hemoglobin_category = interim["Volontaire"]["Catégorie_de_niveau_d'hémoglobine"].mode()[0]
interim["Volontaire"]["Catégorie_de_niveau_d'hémoglobine"].fillna(most_frequent_hemoglobin_category, inplace=True)

# Verify the changes
missing_values = interim["Volontaire"].isnull().sum()
columns_with_missing_values = missing_values[missing_values > 0]
print("Columns with missing values after handling:", columns_with_missing_values)

Columns with missing values after handling: Series([], dtype: int64)

/tmp/ipykernel_3588/258288842.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  interim["Volontaire"]["Groupe_d'âge"].fillna(most_frequent_groupe_d_age, inplace=True)
/tmp/ipykernel_3588/258288842.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  interim["Volontaire"]["Groupe_d'âge"].fillna(most_frequent_groupe_d_age, inplace=True)
/tmp/ipykernel_3588/258288842.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  interim["Volontaire"]["Catégorie_de_niveau_d'hémoglobine"].fillna(most_frequent_hemoglobin_category, inplace=True)
/tmp/ipykernel_3588/258288842.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  interim["Volontaire"]["Catégorie_de_niveau_d'hémoglobine"].fillna(most_frequent_hemoglobin_category, inplace=True)

In [363]:
missing_values = interim["Volontaire"].isnull().sum()
columns_with_missing_values = missing_values[missing_values > 0]
print("Columns with missing values:", columns_with_missing_values)

Columns with missing values: Series([], dtype: int64)

In [364]:
# Define the output path
output_path = Path("../data/processed/processed.xlsx")

In [365]:
# Save the interim data to the output path
with pd.ExcelWriter(output_path) as writer:
    for sheet_name, df in interim.items():
        df.to_excel(writer, sheet_name=sheet_name, index=False)

print(f"Interim data saved to {output_path}")

Interim data saved to ../data/processed/processed.xlsx

In [366]:
# from data_loader import BloodDonationDataLoader
# from data_preprocessor import BloodDonationPreprocessor

# loader = BloodDonationDataLoader()
# preprocessor = BloodDonationPreprocessor(loader.load_raw_excel())
# preprocessor.process()
# preprocessor.save_processed_data()